### ISSUE TITLE
temporary directory not working

### ISSUE THREAD

**Issue by Sanrrone** [ngless-toolkit/ng-meta-profiler#4]
Hi,
I am running the pipeline in an slurm enviroment and even though I specified the `-t` to write into scratch, the pipeline start to write on `~/.local/share/ngless` (specifically /users/valensan/.local/share/ngless/data.tar.gz2776146-0.tmp). Which at some point runs out of disk space.

error log:
```
Exiting after fatal error:
An unhandled error occurred (this should not happen)!

	If you can reproduce this issue, please run your script
	with the --trace flag and report a bug (including the script and the trace) at
		https://github.com/ngless-toolkit/ngless/issues

The error message was: `/users/valensan/.local/share/ngless/data/Modules/igc.ngm/0.9/igc.fna: hPutBuf: permission denied (Quota exceeded)`
```
I tried also by exporting another temporary path but didn't work.

what could I do?
thanks in advance!

**Comment by unode** [comment]
Hi @Sanrrone,

Managing the space in your home folder is outside the scope of the support we can provide here.

That said, you can perhaps workaround the issue by having a [symbolic link](https://en.wikipedia.org/wiki/Symbolic_link) pointing `~/.local/share/ngless` to another location that has more storage capacity.

Hope this helps.
